main:
  - name: Posts
    url: /posts/
    weight: 1
  - name: Tags
    url: /tags/
    weight: 2
  - name: Categories
    url: /categories/
    weight: 3
  - name: About
    url: '/about/'
    weight: 4