baseURL = "https://zacash.cn"
title = "Zac's Blog"
copyright = "Copyright © 2020, Copyright Zac"
languageCode = "en-US"
theme = "indigo"
paginate = 6

[taxonomies]
  tag      = "tags"
  category = "categories"

# Main menu
[menu]

# provide translations in i18n/*.yaml
[[menu.main]]
  weight = 1
  name   = "Tag"
  url    = "/tags"

[[menu.main]]
  weight = 2
  name   = "Category"
  url    = "/categories"

[params]
  Author = "Zac"
  Description = "Android developer blog"
  Subtitle = ""
  Avatar = "images/android-os.png"
  Biography = "🐭"
  ShowBio = true
  PermalinkText = "🔗"
  mainSections = ["post"]
  # Web Monetization only works on secure pages served over HTTPS.
  paymentPointer = ""

  # Contact/social-network identifiers for social icons
  #EmailAddress = "zac_ju@163.com"
  #FacebookUser = "FacebookUserName"
  #FlickrUser = "FlickrUserName"
  GitHubUser = "zac4j"
  #GitLabUser = "GitLabUserName"
  #GlitchUser = "GlitchUserName"
  #KeybaseUser = "KeybaseUserName"
  #LinkedInUser = "LinkedInUserName"
  #MediumUser = "MediumUserName"
  #MicroBlogUser = "MicroBlogUserName"
  #RedditUser = "RedditUserName"
  #StackOverflowUser = "StackOverflowUserName"
  #TumblrUser = "TumblrUserName"
  #TwitterUser = "TwitterUserName"
  #InstagramUser = "InstagramUserName"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "zac_ju@163.com"
    #FlickrUser = "FlickrUserName"
    GitHubUser = "zac4j"
    #TwitterUser = "TwitterUserName"
    #MicroBlogUser = "MicroBlogUserName"
    Country = "China"
    City = "Shanghai"

  [params.endpoints]
    Auth = "https://indieauth.com/auth"
    Token = "https://tokens.indieauth.com/token"
    # To get webmention support, just register at webmention.io and paste the link for endpoint here.
    #Webmention = "https://webmention.io/<yourusername>/webmention"
    # To get micropub support, you'll need to install a Micropub endpoint at your site and put its link there.
    # To get an endpoint with Hugo support, use nanopub: https://github.com/dg01d/nanopub
    # It will probably require some PHP hackery though, as it's fairly basic.
    #Micropub = ""
    # To get microsub support, you can use Aperture from p3k. Either go to https://aperture.p3k.io or self-host it (it's open source!)
    #Microsub = ""